apiVersion: v1
kind: Pod
metadata:
  name: redis-deployment
  app: redis-deployment
  namespace: gcp-final-task
  labels:
    name: redis-deployment
spec:
  containers:
  - name: redis
    image: eu.gcr.io/muhammed-mahoud/redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: gcp-final-task
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-deployment
